CREATE EXTENSION IF NOT EXISTS VECTOR;

-- This table structure must conform to Spring AI Document API
CREATE TABLE IF NOT EXISTS HISTORY_VECTOR
(
    ID        BIGSERIAL PRIMARY KEY,
    METADATA  JSON         NOT NULL,
    CONTENT   TEXT         NOT NULL,
    EMBEDDING VECTOR(1024) NOT NULL
);

CREATE INDEX IF NOT EXISTS HISTORY_VECTOR_INDEX ON HISTORY_VECTOR USING HNSW (EMBEDDING VECTOR_COSINE_OPS);